name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Adjust if your HTML files are in a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
